### ISSUE TITLE
error in timeline with exact time ticks

### ISSUE THREAD

**Issue by stefan242** [hotNipi/node-red-contrib-ui-state-trail#29]
This flow:
![grafik](https://github.com/hotNipi/node-red-contrib-ui-state-trail/assets/46091869/79b62f5e-cb4c-4f36-b221-56ea76a77b9b)

`[{"id":"a71f0e2ace60bb81","type":"ui_statetrail","z":"21766119.96791e","group":"e9339e67.4c3c8","order":2,"width":14,"height":1,"name":"exact time ticks","label":"","states":[{"state":true,"col":"#ff0000","t":"bool","label":""},{"state":false,"col":"#c0c0c0","t":"bool","label":""}],"periodLimit":"14","periodLimitUnit":"3600","timeformat":"HH:mm","tickmarks":"13","exactticks":true,"persist":false,"legend":"0","combine":false,"blanklabel":"Moment ...","x":580,"y":900,"wires":[[]]},{"id":"74a9896a8a4a5f71","type":"inject","z":"21766119.96791e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":920,"wires":[["052aa9fe4d250ba6"]]},{"id":"c10c78169172f7ec","type":"ui_statetrail","z":"21766119.96791e","group":"e9339e67.4c3c8","order":2,"width":14,"height":1,"name":"tick counts","label":"","states":[{"state":true,"col":"#ff0000","t":"bool","label":""},{"state":false,"col":"#c0c0c0","t":"bool","label":""}],"periodLimit":"14","periodLimitUnit":"3600","timeformat":"HH:mm","tickmarks":"13","exactticks":false,"persist":false,"legend":"0","combine":false,"blanklabel":"Moment ...","x":570,"y":940,"wires":[[]]},{"id":"052aa9fe4d250ba6","type":"function","z":"21766119.96791e","name":"function 8","func":"var now = new Date();\nvar today = (now.getMonth() + 1) + \"/\" + now.getDate() + \"/\" + now.getFullYear();\n\nvar startday = Date.parse(today + \" 05:00:00\");\nvar stopday = Date.parse(today + \" 18:00:00\");\n\nvar msg2 = {\n     payload: [\n          { state: false, timestamp: startday },\n          { state: false, timestamp: startday + 1 * 60 * 60 * 1000 },\n          { state: false, timestamp: startday + 6 * 60 * 60 * 1000 },\n          { state: false, timestamp: startday + 9 * 60 * 60 * 1000 },\n          { state: false, timestamp: stopday }\n     ]\n};\n\nreturn msg2;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":360,"y":920,"wires":[["c10c78169172f7ec","a71f0e2ace60bb81"]]},{"id":"e9339e67.4c3c8","type":"ui_group","name":"Fahrzeuge","tab":"abafd6bf.609868","order":1,"disp":false,"width":"16","collapse":false,"className":""},{"id":"abafd6bf.609868","type":"ui_tab","name":"Fahrzeuge","icon":"dashboard","disabled":false,"hidden":false}]`

generates this output:

![grafik](https://github.com/hotNipi/node-red-contrib-ui-state-trail/assets/46091869/c75e121f-bd93-4796-871d-5b7d0f46d1f2)

In the line with the exact time ticks, there is 05:00 instead of 06:00. All other times are correct.

**Comment by hotNipi** [comment]
This is known and can't be fixed.

If you are not using exact ticks, the widget figures out first state which satisfies the period. But it takes to have one state before first actual state you want to show, otherwise there is nothing to start calculations (for positioning and spread) from. 
Widget can't add it by itself. But user can just because of user will know what will be correct properties for that state. 

`[{"id":"a71f0e2ace60bb81","type":"ui_statetrail","z":"02ca79a9a08a0cf4","group":"e9339e67.4c3c8","order":2,"width":14,"height":1,"name":"exact time ticks","label":"","states":[{"state":true,"col":"#ff0000","t":"bool","label":""},{"state":false,"col":"#c0c0c0","t":"bool","label":""}],"periodLimit":"14","periodLimitUnit":"3600","timeformat":"HH:mm","tickmarks":"13","exactticks":true,"persist":false,"legend":"0","combine":false,"blanklabel":"Moment ...","x":1200,"y":960,"wires":[[]]},{"id":"74a9896a8a4a5f71","type":"inject","z":"02ca79a9a08a0cf4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":420,"y":960,"wires":[["052aa9fe4d250ba6"]]},{"id":"c10c78169172f7ec","type":"ui_statetrail","z":"02ca79a9a08a0cf4","group":"e9339e67.4c3c8","order":2,"width":14,"height":1,"name":"tick counts","label":"","states":[{"state":true,"col":"#ff0000","t":"bool","label":""},{"state":false,"col":"#c0c0c0","t":"bool","label":""}],"periodLimit":"14","periodLimitUnit":"3600","timeformat":"HH:mm","tickmarks":"13","exactticks":false,"persist":false,"legend":"0","combine":false,"blanklabel":"Moment ...","x":1190,"y":1000,"wires":[[]]},{"id":"052aa9fe4d250ba6","type":"function","z":"02ca79a9a08a0cf4","name":"function 8","func":"var now = new Date();\nvar today = (now.getMonth() + 1) + \"/\" + now.getDate() + \"/\" + now.getFullYear();\n\nvar startday = Date.parse(today + \" 05:00:00\");\nvar stopday = Date.parse(today + \" 18:00:00\");\n\nvar msg2 = {\n     payload: [         \n          { state: false, timestamp: startday },\n          { state: false, timestamp: startday + 1 * 60 * 60 * 1000 },\n          { state: false, timestamp: startday + 6 * 60 * 60 * 1000 },\n          { state: false, timestamp: startday + 9 * 60 * 60 * 1000 },\n          { state: false, timestamp: stopday }\n     ]\n};\n\nreturn msg2;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":600,"y":960,"wires":[["a71f0e2ace60bb81","af1a40e7240dcdb0"]]},{"id":"af1a40e7240dcdb0","type":"function","z":"02ca79a9a08a0cf4","name":"add one element to the beginning of the array","func":"let first = msg.payload[0]\nmsg.payload.unshift({state:first.state,timestamp:first.timestamp - 1000})\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":890,"y":1000,"wires":[["c10c78169172f7ec"]]},{"id":"e9339e67.4c3c8","type":"ui_group","name":"Fahrzeuge","tab":"abafd6bf.609868","order":1,"disp":false,"width":"16","collapse":false,"className":""},{"id":"abafd6bf.609868","type":"ui_tab","name":"Fahrzeuge","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by stefan242** [comment]
> If you are not using exact ticks,

Sorry, but the error IS in the line with the exact time ticks! the first tick should be 06:00 (am), but it shows 05:00!

**Comment by hotNipi** [comment]
V1.0.2 available
