### ISSUE TITLE
Need tooltips and persistence

### ISSUE THREAD

**Issue by swilson86** [hotNipi/node-red-contrib-ui-state-trail#9]
Very nice widget but lacks 2 features. A tooltip to show the date/time of an event, and better persistence in holding the data (just like the node-red standard graphs have).

Background: A standard node-red graph will not cleanly show a state event such as when a door is open/closed, etc. These graphs when set to a range of 0 (door closed) to 1 (door open) for example always have the graduations between 0 and 1 displayed thus wasting a lot of screen space. However, these graphs do have better built in persistence (it will hold the data during a screen refresh or an update to a different node) and a tooltip to see the exact time of an event. If your widget would do those things it would be invaluable.

**Comment by hotNipi** [comment]
Hi. I can't be agree with the luck of persistence. Yes it really depends on how your node-red is set up. If you are using the file-based persistence option and configure the state-trail to use it, then it has almost always stored data. I say almost, cos there is some rare situation where node-red fails to store. 
![image](https://user-images.githubusercontent.com/35291460/80799163-cd1cab80-8bae-11ea-96b3-40ec2e24e79b.png)
 
For tooltip, the plan was dropped. You can always use https://flows.nodered.org/node/node-red-contrib-ui-contextmenu to show the data in the format you want.

![image](https://user-images.githubusercontent.com/35291460/80799353-5502b580-8baf-11ea-9085-559a793a2b88.png)


Simple flow with contextmenu usage

`[{"id":"8938dfa.a07832","type":"inject","z":"3dd56201.af994e","name":"","topic":"","payload":"","payloadType":"date","repeat":"2","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":120,"wires":[["3ed26a42.eaa116"]]},{"id":"3ed26a42.eaa116","type":"random","z":"3dd56201.af994e","name":"","low":"1","high":"3","inte":"true","property":"payload","x":370,"y":120,"wires":[["c08f6957.58b878"]]},{"id":"c08f6957.58b878","type":"ui_statetrail","z":"3dd56201.af994e","group":"e16e41b4.24e6d","order":0,"width":"6","height":"2","name":"","label":"","states":[{"state":1,"col":"#009933","t":"num","label":"ONE"},{"state":2,"col":"#999999","t":"num","label":"TWO"},{"state":3,"col":"#ff6666","t":"num","label":"THREE"}],"periodLimit":1,"periodLimitUnit":"60","timeformat":"HH:mm:ss","tickmarks":4,"persist":true,"legend":1,"combine":true,"blanklabel":"","x":510,"y":120,"wires":[["4afcb1bf.30dd7"]]},{"id":"33245713.e56c08","type":"ui_context_menu","z":"3dd56201.af994e","group":"e16e41b4.24e6d","order":1,"width":0,"height":-1,"fontSize":16,"position":"msg","outputField":"payload","xCoordinate":50,"yCoordinate":50,"menu":"msg","menuItems":[{"id":"","icon":"","label":"","topic":"","payload":"","payloadType":"str","visible":true,"enabled":true}],"colors":"theme","textColor":"#000000","backgroundColor":"#ffffff","borderColor":"#626262","intervalLength":"5","intervalUnit":"secs","startTimerAtOpen":false,"startTimerAtLeave":true,"stopTimerAtEnter":true,"name":"","x":580,"y":200,"wires":[[]]},{"id":"4afcb1bf.30dd7","type":"function","z":"3dd56201.af994e","name":" for contextmenu","func":"msg.menu = [{text:msg.payload.label+\" Dur: \"+msg.payload.duration+\"ms\"}]\nmsg.position = {x:msg.clickCoordinates.screenX,y:msg.clickCoordinates.screenY-100}\nreturn msg;","outputs":1,"noerr":0,"x":400,"y":200,"wires":[["33245713.e56c08"]]},{"id":"e16e41b4.24e6d","type":"ui_group","z":"","name":"Default","tab":"8d0983ef.83d71","order":1,"disp":true,"width":"6","collapse":false},{"id":"8d0983ef.83d71","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by Bono1969** [comment]
@hotNipi 
i also play arround with tooltips. So i found this case. I installed this flow, but i get an error from the contextmenu function block.
![screenX](https://user-images.githubusercontent.com/37637519/89292002-de68ce80-d65b-11ea-9063-2ebccbf8f502.png)

**Comment by hotNipi** [comment]
This is probably because of that old example is not up to date.
It uses msg.clickCoordinates but that property should be changed to msg.event
The breaking change is mentioned here: https://github.com/hotNipi/node-red-contrib-ui-state-trail#alert

The content of function to prepare data for contextmenu  should be like this

`msg.menu = [{text:msg.payload.label+" Dur: "+msg.payload.duration+"ms"}]
msg.position = {x:msg.event.screenX,y:msg.event.screenY-100}
return msg;`

**Comment by Bono1969** [comment]
@hotNipi 
much better !
One Problem left. Should the Pupup appear in the area of the Mouseclick?
Mine appears at the base and left?

**Comment by hotNipi** [comment]
You can play with msg.position = {x:msg.event.screenX,y:msg.event.screenY-100}
msg.event.screenX and msg.event.screenY are exact mouse coordinates, 

I have currently 2 monitors with different sizes and that requires different setup of coordinates

`msg.position = {x:msg.event.clientX,y:msg.event.bbox[1] -60}`

So there is many possibilities how to manage the position. 
msg.event has all needed properties for that.
![image](https://user-images.githubusercontent.com/35291460/89301305-36123480-d672-11ea-9e0c-893908544675.png)



Next it is feeded to contextmenu and the responsibility goes over.  State-trail can't force any drawing rules for contextmenu node.

**Comment by Bono1969** [comment]
@hotNipi 
You'r right and that was also the reason for me to use the normal notification node.
I worked long and hard (because i have no plan about HTML, Java...) for the Solution you can see in the added Testflow.
When you have a look on that maybe you are laughing (like on your Foto) about this. Maybe you know how to organize the code better.
You also can think about to add this Example to your code.
Regards and thanks for your Help (i have already given you a star).

`[{"id":"b684bdf3.161ee","type":"tab","label":"State Trail (Demo)","disabled":false,"info":""},{"id":"a11f50a6.d24d3","type":"inject","z":"b684bdf3.161ee","name":"","topic":"","payload":"","payloadType":"date","repeat":"5","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":160,"wires":[["68c535ed.a4525c"]]},{"id":"f792f8f0.b5f6a8","type":"ui_statetrail","z":"b684bdf3.161ee","group":"89bbb139.70e1b","order":0,"width":"6","height":"2","name":"","label":"","states":[{"state":1,"col":"#009933","t":"num","label":"ONE"},{"state":2,"col":"#999999","t":"num","label":"TWO"},{"state":3,"col":"#ff6666","t":"num","label":"THREE"}],"periodLimit":1,"periodLimitUnit":"60","timeformat":"HH:mm:ss","tickmarks":4,"persist":false,"legend":1,"combine":true,"blanklabel":"","x":480,"y":160,"wires":[["261254d4.7c4a0c","2d1416c8.598cfa"]]},{"id":"b851a5dd.fffc38","type":"ui_context_menu","z":"b684bdf3.161ee","group":"89bbb139.70e1b","order":1,"width":0,"height":-1,"fontSize":16,"inputPositionXField":"position.x","inputPositionXType":"msg","inputPositionYField":"position.y","inputPositionYType":"msg","outputField":"payload","inputMenuField":"menu","inputMenuType":"msg","menuItems":[{"id":"","icon":"","label":"","topic":"","payload":"","payloadType":"str","visible":true,"enabled":true}],"colors":"theme","textColor":"#000000","backgroundColor":"#ffffff","borderColor":"#626262","intervalLength":"5","intervalUnit":"secs","startTimerAtOpen":false,"startTimerAtLeave":true,"stopTimerAtEnter":true,"name":"","x":900,"y":200,"wires":[[]]},{"id":"261254d4.7c4a0c","type":"function","z":"b684bdf3.161ee","name":" for contextmenu","func":"msg.menu = [{text:msg.payload.label+\" Dur: \"+msg.payload.duration+\"ms\"}];\nmsg.position = {x:msg.event.screenX,y:msg.event.screenY-100}; \nreturn msg;","outputs":1,"noerr":0,"x":680,"y":200,"wires":[["b851a5dd.fffc38"]]},{"id":"68c535ed.a4525c","type":"random","z":"b684bdf3.161ee","name":"","low":"1","high":"3","inte":"true","property":"payload","x":320,"y":160,"wires":[["f792f8f0.b5f6a8"]]},{"id":"2d1416c8.598cfa","type":"function","z":"b684bdf3.161ee","name":" for notification","func":"msg.topic = msg.payload.label;\n\nvar start;\nvar ende;\n\nvar now     = new Date(msg.payload.timestamp); \nvar hour    = now.getHours();\nvar minute  = now.getMinutes();\nvar second  = now.getSeconds();\nif(hour.toString().length == 1) {\nvar hour = '0'+hour;\n}\nif(minute.toString().length == 1) {\nvar minute = '0'+minute;\n}\nif(second.toString().length == 1) {\nvar second = '0'+second;\n}\nstart = hour+':'+minute+':'+second;\n\nvar now1     = new Date(msg.payload.end); \nvar hour1    = now1.getHours();\nvar minute1  = now1.getMinutes();\nvar second1  = now1.getSeconds();\n\nif(hour1.toString().length == 1) {\nvar hour1 = '0'+hour1;\n}\nif(minute1.toString().length == 1) {\nvar minute1 = '0'+minute1;\n}\nif(second1.toString().length == 1) {\nvar second1 = '0'+second1;\n}\nende = hour1+':'+minute1+':'+second1;\n\nvar duration = Math.round((msg.payload.duration/60000)*10)/10;\n\nmsg.payload = \"<li> Beginn:&nbsp;&nbsp;&nbsp; \"+start+\"</li> <li> Ende:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \"+ende+\"</li> <li> Dauer:&nbsp;&nbsp;&nbsp;&nbsp; \"+duration+\" min</li>\";\nreturn msg;","outputs":1,"noerr":0,"x":680,"y":120,"wires":[["453f2a02.971864"]]},{"id":"453f2a02.971864","type":"ui_toast","z":"b684bdf3.161ee","position":"dialog","displayTime":"3","highlight":"","sendall":true,"outputs":1,"ok":"OK","cancel":"","raw":true,"topic":"","name":"Notification dialog","x":890,"y":120,"wires":[[]]},{"id":"5b412667.791c18","type":"comment","z":"b684bdf3.161ee","name":"Testflow","info":"","x":120,"y":60,"wires":[]},{"id":"89bbb139.70e1b","type":"ui_group","z":"","name":"Trail","tab":"f2c35526.03cbe8","order":1,"disp":true,"width":"6","collapse":false},{"id":"f2c35526.03cbe8","type":"ui_tab","z":"","name":"State Trail (Demo)","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by hotNipi** [comment]
Thank you for creating this example. It shows perfectly how the data from widget can be used. 
Many thanks for you contribution. 👍

**Comment by hotNipi** [comment]
Solution found
